apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-k8s
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: chart/
    repoURL: https://github.com/zschweinfurth/spark_k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true